### ISSUE TITLE
Select2 chained dropdown investigation

### ISSUE THREAD

**Issue by lenamtl** [rubentd/dirrty#11]
How to reproduce:
have a chained dropdowns using Select2 
have the option allowClear: true,
and .select2-single

Let say country, state, city
on page load no value selected
select a country, click on the clear
Now State and City are marked as dirrty, Country is marked as clear
the 3 fields should be marked as clean

**Comment by rubentd** [comment]
WIll look into it. Thanks for reporting

**Comment by lenamtl** [comment]
I did some extra tests today, and it happening to any dropdown of the form if in the form have some chained dropdown using Ajax (the problem occurred also on non-chained dropdown).

I have another form with non-chained dropdown and it's trigger the d.checkValues(); correctly...

I will do more test tomorrow

**Comment by lenamtl** [comment]
Hi, I did more test and update the problem.
I'm not sure if this is a Select2 issue or my code ...

I have tried these with no luck
```
d.form.find("select").on('mouseup mousedown', function(){
d.checkValues();
```
```
d.form.find("select").on('cleared', function(event){
	d.checkValues();
```
I'm looking for another way to trigger the `d.checkValues();`  for the select
I cannot use .trigger('change') because I'm already using on change in my code to fill the appropriate dropdown based on the country.

**Comment by lenamtl** [comment]
How can I add trigger the d.checkValues(); as it is outside the scope
I cannot trigger on change as it is conflicting with the chained dropdown.

Is there a way to check the  .empty() method similar to this?
```
d.form.find("select").on('empty', function(){
	d.checkValues();
});  
```

**Comment by lenamtl** [comment]
Ok I figured out what the problem is 
my code do this to clear the field when selecting a country  $('#quote_city_id').empty();
so if I consol.log the value is not considered empty but NULL...
So the field was fisrt " " then NULL so the data changed...

To fixt this, rght sfter $('#quote_city_id').empty();  I prepend an empty value like this `$('#quote_city_id').prepend("<option value='' selected='selected'>Select</option>");` so the value get back to empty
