### ISSUE TITLE
Question about alert message text

### ISSUE THREAD

**Issue by lenamtl** [rubentd/dirrty#2]
Hi,

I need to translate the alert dialog message.
Where are they set?

I only find a  message inside the JS which is not corresponding
**You have unsaved changes**

VS what it is displayed

**Do you want to leave this site.
Changes you made may not be saved.
Leave  Stay** (buttons)

Here is my actual code 

```
$("#edit").dirrty().on("dirty", function(){
    $("#save").removeAttr("disabled");
    }).on("clean", function(){
    $("#save").attr("disabled", "disabled");
});
```

Thanks

**Comment by rubentd** [comment]
You can set-up the message with the 'leavingMessage' option:

$("#edit").dirrty({
  leavingMessage: 'You have unsaved changes'
});

**Comment by lenamtl** [comment]
Hi,

I have tried this maybe there is a syntax error

```
$("#edit").dirrty({
                    leavingMessage: 'You have unsaved changes'
                    }).on("dirty", function(){

                        $("#save").removeAttr("disabled");
                        }).on("clean", function(){

                        $("#save").attr("disabled", "disabled");
                        });
```

I'm always getting this dialog see attach file.
This text and button come from browser? can we customize it?
![alert](https://cloud.githubusercontent.com/assets/2241324/16563782/ee177124-41d1-11e6-9f3a-ee608d18d1e0.png)

**Comment by rubentd** [comment]
It seems Chrome is not allowing to customise that message anymore:
https://www.chromestatus.com/feature/5349061406228480

**Comment by lenamtl** [comment]
Do you plan to replace onbeforeunload by something else or other way to display message?

**Comment by rubentd** [comment]
At least not at the moment. If you find some alternative, your contribution will be truly appreciated

**Comment by lenamtl** [comment]
I have made several search and try several script with no luck and most of the time we cannot customize the message because it render by the browser.
